### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by prerna-grg** [lyndonzheng/Pluralistic-Inpainting#1]
Hey,
I am trying to test your code but I am getting the following error. 
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from dataloader import data_loader
ImportError: No module named dataloader

Could you please help ?

**Comment by lyndonzheng** [comment]
Try creating a file named "__init__.py" in the "dataloder" directory. I guess this is the problem of python path.

**Comment by prerna-grg** [comment]
@lyndonzheng  thanks a lot
