### ISSUE TITLE
Support multiple GPU training?

### ISSUE THREAD

**Issue by LightGal** [lyndonzheng/Pluralistic-Inpainting#10]
Hi, I was wondering whether you have tested multi-GPU training? which is not clarified in Readme. Thanks in advance~

**Comment by lyndonzheng** [comment]
@LightGal Thanks for your interesting. We trained the model with multi-GPU, but the D_loss will become zero in some situations. The final performance of multi-GPU training is worse than the performance of single-GPU training.

**Comment by LightGal** [comment]
Thanks for your quick reply, it really helps.

BTW, I was wondering how much time it would take to train on dataset Paris or celebA-HQ until convergence using single-GPU?
