### ISSUE TITLE
Inference Time

### ISSUE THREAD

**Issue by srika91** [lyndonzheng/Pluralistic-Inpainting#11]
Hello lyndonzheng,

First of all,this is Awesome work!
I just have one doubt.What is the inference time you are getting to generate 50 samples for a single person.are there ways/tricks we can speed up this process?I am getting inference time of 0.43 seconds if I want to generate 1 sample for three person images. I am using 1080Ti.

regards
srikanth

**Comment by lyndonzheng** [comment]
@srika91 We test our model with batchsize=8, and nsampling=50 on single 1080Ti GPU, i7-6900 CPU @3.2GHz. It takes average 28.50 seconds for each batchsize, which means our testing time on GPU is 0.071 seconds for each sample. May be you can try to test the model with a large batchsize.

**Comment by srika91** [comment]
Hello lyndonzheng,
Thank you for the reply.I am also getting close to that value,12.04seconds now
