### ISSUE TITLE
Documentation doesn't specify...

### ISSUE THREAD

**Issue by darekmm** [lyndonzheng/Pluralistic-Inpainting#12]
1. Can you use the GUI with own models or only pretrained?
2. Running train with --mask_type 0  results in error. Should training for center hole mask be performed differently?

**Comment by lyndonzheng** [comment]
@darekmm 1. You can use the models with your models. You just need to modify the model_name and path in "ui_model.py". 2. As for the --mask_type, you may need to modify this in "base_options.py".

**Comment by darekmm** [comment]
Okay thanks! Keep up the great job!
