### ISSUE TITLE
required epoch to train

### ISSUE THREAD

**Issue by HilmiK** [lyndonzheng/Pluralistic-Inpainting#13]
In your datasets, how many epochs did you need to train to get these reasonable results ?

Thanks.

**Comment by lyndonzheng** [comment]
@HilmiK You can find the training details in the appendix of our arxiv paper. "_Training models for centered holes of Paris and CelebA-HQ takes roughly 3 days, while for ImageNet and Places2 it takes roughly 2 weeks. On the other hand, training models for random irregular and un-centered holes takes about twice the time compared to models for centered holes._"
