### ISSUE TITLE
image inpainting quality assessment

### ISSUE THREAD

**Issue by LightGal** [lyndonzheng/Pluralistic-Inpainting#14]
Hi, I understand that this is not actually an "issue" but could you help me:

1. How do you compute the PSNR, TV loss and IS metrics? (Using what repo or package?
2. When you compute the IS, is the unmasked area GT or generated?

I am a novice in this area. I will be appreciated if you could help me with that. Thanks in advance~

**Comment by lyndonzheng** [comment]
@LightGal 1. The metrics code can be found in "utils/evaluation.py" and "evaluations/inception_score_torch.py"
2. To calculate the IS, the unmasked area is GT from the original masked inputs. 
If you have any other questions about this ares, please feel free to discuss with me.

**Comment by LightGal** [comment]
Thanks a million for your kind instructions~ Your answers are clear and sound. Issue closed.
