### ISSUE TITLE
How to continue training?

### ISSUE THREAD

**Issue by darekmm** [lyndonzheng/Pluralistic-Inpainting#15]
running python3 train.py --continue_train results in the following error:

```
 File "train.py", line 12, in <module>
    dataset = dataloader(opt)
  File "/home/darek/Pluralistic/dataloader/data_loader.py", line 78, in dataloader
    datasets = CreateDataset(opt)
  File "/home/darek/Pluralistic/dataloader/data_loader.py", line 12, in __init__
    self.img_paths, self.img_size = make_dataset(opt.img_file)
  File "/home/darek/Pluralistic/dataloader/image_folder.py", line 18, in make_dataset
    paths, size = make_dataset_dir(path_files)
  File "/home/darek/Pluralistic/dataloader/image_folder.py", line 47, in make_dataset_dir
    assert os.path.isdir(dir), '%s is not a valid directory' % dir
AssertionError: /data/dataset/train is not a valid directory
```

This is probably due to --img_file not being set; so what parameters need to be specified when continuing training? If I run it with just same parameters including --name it seems to start anew from step 1.

Also one more question: does the train.py perform data augmentation by default?

**Comment by lyndonzheng** [comment]
@darekmm This error comes from your dataset is invalid. For continue training, you just use "python train.py --name # --img_file # --continue_train"

**Comment by darekmm** [comment]
The dataset is valid; I used the same one as in the initial training. 
The error correctly states that I didn't specify img_file at all the second time. Anyway it seems to be working with --continue_train. Great!
