### ISSUE TITLE
Higher res input?

### ISSUE THREAD

**Issue by darekmm** [lyndonzheng/Pluralistic-Inpainting#17]
Can the image_size be specified upwards? I mean testing on images 512x512 or bigger?

**Comment by lyndonzheng** [comment]
@darekmm The model cannot be tested on heigher resolution input, because the feature distribution size is 8*8. Currently, we try to train this "pluralistic" idea to arbitrary resolution.

**Comment by darekmm** [comment]
Would be awesome to try on higher resolutions. Good luck!

**Comment by lyndonzheng** [comment]
Thanks. Hope we can provide this in the future.
