### ISSUE TITLE
bad outputs when testing

### ISSUE THREAD

**Issue by shihaobai** [lyndonzheng/Pluralistic-Inpainting#18]
dear author,when i tried to test your model by images in celeba, i got this error:
latest_net_G.pth
G:\Pluralistic-Inpainting\model\checkpoints\celeba_random\latest_net_G.pth
Pretrained network G has fewer layers; The following are not initialized:
['attn1', 'decoder0', 'decoder1', 'decoder2', 'decoder3', 'decoder4', 'generator', 'out1', 'out2', 'out3', 'out4']
why can't i load the pretrained model?  i will appreciate it very much if you can help me.

**Comment by lyndonzheng** [comment]
@shihaobai Currently, the pretrained model can only be tested on the GPU. Do you test it on the GPU? Besides, if the issues cannot be solved in this way, please you provide the testing command and full error information.

**Comment by shihaobai** [comment]
it does work! Thank you for your help!

**Comment by chen849157649** [comment]
> it does work! Thank you for your help!

brother , where modify code load model use the GPU, thank you

**Comment by shihaobai** [comment]
You needn't modify the code. Just run it in an environment with GPU.

**Comment by chen849157649** [comment]
Thank you，before had changed gpu_IDs to -1，so  load pretrained model  error。发自我的华为手机-------- 原始邮件 --------主题：Re: [lyndonzheng/Pluralistic-Inpainting] bad outputs when testing (#18)发件人：shihaobai 收件人：lyndonzheng/Pluralistic-Inpainting 抄送：chenguitao <849157649@qq.com>,Comment You needn't modify the code. Just run it in an environment with GPU.
