### ISSUE TITLE
AttributeError: 'ui_model' object has no attribute 'model'

### ISSUE THREAD

**Issue by leafchenh** [lyndonzheng/Pluralistic-Inpainting#19]
Running 'ui_main' prompts an error, why

**Comment by lyndonzheng** [comment]
@leafchenh Currently, the pretrained model can only be tested on the GPU. Besides, if the issues cannot be solved in this way, please you provide the testing command and full error information.

**Comment by leafchenh** [comment]
I found the problem and solved it，But after executing  'python train.py --name celeba_random --img_file your_image_path' indicates that my torch vision has no Resize attribute.

AttributeError: module 'torchvision.transforms' has no attribute 'Resize'.
My torchvision version is 0.1.6
