### ISSUE TITLE
doubt in mask color

### ISSUE THREAD

**Issue by abhishekdawas10** [lyndonzheng/Pluralistic-Inpainting#2]
@lyndonzheng  I am trying to test your code on my images, what kind of mask should be used for testing .. black-background white-patch (vice versa) , grey patch ???

**Comment by lyndonzheng** [comment]
@abhishekdawas10 The mask should be black-background with white-patch as masked regions. You can directly use the GUI to test the model and save the mask and outputs.

**Comment by sporterman** [comment]
@abhishekdawas10 what about you test results?  i always get pictures like those, is there any parameters i shoud change? 
![image](https://user-images.githubusercontent.com/13059352/55381265-4a619100-5555-11e9-8a83-f815f3738f71.png)
![image](https://user-images.githubusercontent.com/13059352/55381283-58afad00-5555-11e9-8c23-3009e941409a.png)
