### ISSUE TITLE
Suggest adding requirements.txt

### ISSUE THREAD

**Issue by Mainvooid** [lyndonzheng/Pluralistic-Inpainting#20]
opencv-contrib-python
imageio
PyQt5
torch
torchvision
visdom
future

**Comment by Mainvooid** [comment]
maybe should adding a hint:
need to be turned on before use:
python -m visdom.server

**Comment by lyndonzheng** [comment]
@Mainvooid Thanks for your suggestion, we will add this in the next version, which will be released soon.
