### ISSUE TITLE
ConnectionRefusedError: [WinError 10061]

### ISSUE THREAD

**Issue by Mainvooid** [lyndonzheng/Pluralistic-Inpainting#21]
base_options.py 
```python
parser.add_argument('--display_port', type=int, default=8095, help='visidom port of the web display')
```
Change the default port to 8097(visdom default) and the problem is solved.

torch 1.1.0
visdom 0.1.8.8

**Comment by lyndonzheng** [comment]
@Mainvooid Thanks for these good suggestions. We have modified it.
