### ISSUE TITLE
Can I do training on google colab?

### ISSUE THREAD

**Issue by pixpixpox** [lyndonzheng/Pluralistic-Inpainting#24]
My laptop configuration is too low for the training (GPU - 2GB; RAM - 8GB). So is there any way to run the training on google colab as they provide free 1**2GB NVIDIA Tesla K80 GPU**? If yes, can you tell me what to do and how to do?
And what is the minimum configuration requirements needed to train the model?
-Thanks

**Comment by lyndonzheng** [comment]
@pixpixpox I have not tried this on google colab.  The Tesla K80 GPU is enough for the training. The requirements can be found in #20
