### ISSUE TITLE
can't get good results when testing my own pictures

### ISSUE THREAD

**Issue by yangwenshuo-star** [lyndonzheng/Pluralistic-Inpainting#28]
I can get good results when I use the images in celaba-hq.But when I tested with my own pictures, I got a bad result, and I've used the image editing tool to cut the characters,so can you guide me how to do this? thanks.

**Comment by lyndonzheng** [comment]
@yangwenshuo-star For my own face image, I follow the [growing gan](https://github.com/tkarras/progressive_growing_of_gans) to cut the face regions. You must make sure your face similar to this dataset with high resolution. I also try to use Obama and Trump for my demo, the images  I selected from the website also very high resolution.  Besides, most of the faces in celeba-hq are west face, the model will transfer my eyes and nose like the europe face.

**Comment by yangwenshuo-star** [comment]
thank you，I will try it.
