### ISSUE TITLE
Meaning of 50 outputs

### ISSUE THREAD

**Issue by prerna-grg** [lyndonzheng/Pluralistic-Inpainting#3]
In options/test_options.py there is a parameter nsampling which refers to number of outputs generated for an image-mask pair. What is the logic behind these **multiple** outputs?

**Comment by lyndonzheng** [comment]
@prerna-grg When the masked regions are larged, different people will draw different details for these regions. Our main novelty is to provide **multiple** and **diverse** results for one masked images.

**Comment by prerna-grg** [comment]
@lyndonzheng My questions was how are these outputs different. Is there a source of randomness, and if yes in what?
Basically I am having problem in understanding the semantic meaning of multiple outputs

**Comment by lyndonzheng** [comment]
@prerna-grg Yes, we will sample from a predicted distribution to get random results. For face completion, the high-level semantic information will be same. But the face details will be different.
