### ISSUE TITLE
Image amount of testing split on CelebA-HQ dataset

### ISSUE THREAD

**Issue by andrewkgs** [lyndonzheng/Pluralistic-Inpainting#30]
Hello, sorry to bother you.

I created the CelebA-HQ dataset by following the steps in this GitHub repository (https://github.com/nperraud/download-celebA-HQ), and I split the dataset into training, validation, and testing split as you described in #4 (label 0 as training, label 1 as validation, and label 2 as testing). Eventually, I got 24183/2993/2824 images for training/validation/testing split.

The README.md file in this repository shows that your testing set contains 2796 images; however, I got different amount of testing images.

Below is the list of my testing split. Could you please provide your testing images list or point out any possible mistake I might have made while generating CelebA-HQ dataset? Thank you very much!

My list of testing split: [test_split.txt](https://github.com/lyndonzheng/Pluralistic-Inpainting/files/3625519/test_split.txt)

**Comment by lyndonzheng** [comment]
@andrewkgs This is the training/validation/testing file [list_eval_partition](https://drive.google.com/drive/folders/0B7EVK8r0v71pdjI3dmwtNm5jRkE). We select HQ images in that list as our training/validation/[celeba_test.txt](https://github.com/lyndonzheng/Pluralistic-Inpainting/files/3630918/celeba_test.txt). But I use the original index of celeba.

**Comment by andrewkgs** [comment]
Thank you for your reply.

Because the [celeba_test.txt](https://github.com/lyndonzheng/Pluralistic-Inpainting/files/3630918/celeba_test.txt) you provided contains all testing images (19962 images in total) in the original CelebA dataset, I'm not sure which images did you choose as the CelebA-HQ testing split.

I generate a new list of testing images of CelebA-HQ dataset with the original CelebA dataset index here ([CelebA_HQ_test_split_original_index.txt](https://github.com/lyndonzheng/Pluralistic-Inpainting/files/3633961/CelebA_HQ_test_split_original_index.txt)).

Below are the steps that how I obtain this list:

First, I download [list_eval_partition](https://drive.google.com/drive/folders/0B7EVK8r0v71pdjI3dmwtNm5jRkE) from CelebA dataset and [image_list](https://drive.google.com/open?id=0B4qLcYyJmiz0U25vdEVIU3NvNFk) from CelebA-HQ (acquired from the repository of [Growing GANs](https://github.com/tkarras/progressive_growing_of_gans)).

Since the testing image in CelebA dataset named from "182638.jpg" to "202599.jpg," I write the Python script below to extract CelebA-HQ testing images using the original index of CelebA dataset. 
```
import numpy as np

list_CelebA_HQ = np.genfromtxt("image_list.txt", dtype=str)[1:, 2]

HQ_test_img_name = []
for i, img_name in enumerate(list_CelebA_HQ):
    img_num = int(img_name[:-4])
    if img_num >= 182638 and img_num <= 202599:
        HQ_test_img_name.append(img_name)

with open("CelebA_HQ_test_split_original_index.txt", 'w') as f:
    for name in sorted(HQ_test_img_name):
        f.write("{}\n".format(name))
```
The list of CelebA-HQ testing split that I obtained consists of 2824 images, instead of 2796 images you write on the README.md file. Would you please provide your CelebA-HQ list which contains 2796 images? Thank you very much!

**Comment by lyndonzheng** [comment]
@andrewkgs Thanks for your question. I made a mistake for the testing number in README.md. I have uploaded my training/val/testing list for this Celeba-HQ dataset.
