### ISSUE TITLE
Can I test on non-square images?

### ISSUE THREAD

**Issue by sblack12** [lyndonzheng/Pluralistic-Inpainting#31]
I know that this doesn't work for high resolution images, but is it possible to use images that  aren't square (for example: 256 x 184) ? 

I'm receiving the following error when doing so:

    context_flow = torch.bmm(pre.view(B, -1, W*H), attention.permute(0, 2, 1)).view(B, -1, W, H)
    RuntimeError: shape '[1, -1, 640]' is invalid for input of size 94208

**Comment by lyndonzheng** [comment]
@sblack12 Since the random vector is sampled from 8*8 size. The current verion can not get high quality results for other input size. We still work on this arbitrary input size.

**Comment by sblack12** [comment]
Cool, thanks!
