### ISSUE TITLE
preprocess

### ISSUE THREAD

**Issue by thinkerthinker** [lyndonzheng/Pluralistic-Inpainting#38]
i'am confused about pre-process steps at pluralistic_model.py.
at function set_input, why u use self.img_truth = self.img * 2 - 1?
why not self.img_truth = self.img?
is there any meanings for results?

**Comment by lyndonzheng** [comment]
@thinkerthinker This pre-process is for the image generation that normalizes the value to (-1,1). In this way, we can use the tanh function, which makes the generation more stable.

**Comment by thinkerthinker** [comment]
thank you for your quick reply!
