### ISSUE TITLE
About output images

### ISSUE THREAD

**Issue by tuotuotu** [lyndonzheng/Pluralistic-Inpainting#40]
When I use Pretrained models to test(GUI), the results like these, it doesn't work well. Sorry to bother you, but I really don't know what's wrong.  [
![proble](https://user-images.githubusercontent.com/45143774/70708956-b61c1080-1d16-11ea-851b-92f5bc2f58d5.png)
](url)

**Comment by lyndonzheng** [comment]
@tuotuotu This is a duplicate of https://github.com/lyndonzheng/Pluralistic-Inpainting/issues/9

**Comment by tuotuotu** [comment]
Thank you for your quick reply!
