### ISSUE TITLE
Can You Help Me.

### ISSUE THREAD

**Issue by Ikbalmursidin22** [lyndonzheng/Pluralistic-Inpainting#41]
how to make this application a web application. like your demo?

Thank's

**Comment by lyndonzheng** [comment]
@ikbalmusidin The web application is based on a javascript file. The original code comes from [deepfill](http://jiahuiyu.com/deepfill/). You can modify the .js file for your own purpose. If you do use the .js file provided in our website, you also need to cite [deepfill](http://jiahuiyu.com/deepfill/).
