### ISSUE TITLE
AttributeError: 'ui_model' object has no attribute 'img_out'

### ISSUE THREAD

**Issue by MrLassagna** [lyndonzheng/Pluralistic-Inpainting#42]
total number of parameters: 1.591 M
initialize network with orthogonal
model [Pluralistic] was created
Traceback (most recent call last):
  File "C:\Projects\Image_Reconstruction\Pluralistic\gui\ui_model.py", line 83, in show_result
    new_pil_image = Image.fromarray(util.tensor2im(self.img_out.detach()))
AttributeError: 'ui_model' object has no attribute 'img_out'

**Comment by lyndonzheng** [comment]
@MrLassagna The problem mentioned above seems to come from the platform. I have not tried the code on windows. You need to debug the code on the new system.

**Comment by MrLassagna** [comment]
I tried to set up Linux like tens of times. It simply doesn't want to allow me to use my NVIDIA GPU. That's another issue I am facing with Ubuntu.
