### ISSUE TITLE
Question about the output of Discriminator

### ISSUE THREAD

**Issue by samblack15** [lyndonzheng/Pluralistic-Inpainting#44]
When I feed a 1x3x512x512 tensor to the discriminator (representing a single RGB image with height and width = 512) the output is a 1x1x14x14 tensor. Why is it not just one single number? How can I interpret this discriminator output to determine whether it thinks that the image is real or fake?

**Comment by lyndonzheng** [comment]
@samblack15 This is a duplicate of the [issue in PatchGAN](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/39).
