### ISSUE TITLE
Question about the setting of nsampling

### ISSUE THREAD

**Issue by wj320** [lyndonzheng/Pluralistic-Inpainting#58]
Thank you for your great project！
When I set --nsampling=1, the results are very poor, why is it that?

**Comment by lyndonzheng** [comment]
@wj320 Could you please share the examples?

**Comment by wj320** [comment]
I think it is not resulted by "nsampling=1",  it may be the image size instead.
I set --loadSize 128 128 --fineSize 128 128, some results are shown in:
链接：https://pan.baidu.com/s/12SaNFvGvFQeB2I_MmuyHfA 
提取码：vfdk 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by lyndonzheng** [comment]
@wj320 As the samples come from the different random vectors, our network currently can only generate fixed resolution results, rather than arbitrary sizes.

**Comment by wj320** [comment]
Thank you for your reply!
