### ISSUE TITLE
About diversity measure

### ISSUE THREAD

**Issue by laolongboy** [lyndonzheng/Pluralistic-Inpainting#59]
In the paper, 'The average score is calculated between 50K pairs generated from a sampling of 1K center-masked images.' 

I am confused about how to compute this diversity measure. 

For every single center-masked image, I compute LPIPS metric between 50 generated results and the ground truth. Then get the mean value of 1K center-masked images. But the results are quite different from the paper. Did I get it wrong? Would you show this part of code? Thanks!

**Comment by lyndonzheng** [comment]
Hi @laolongboy, for the diversity score, we only calculate the LPIPS for the center regions. Besides, we sampled 50K pairs in two files and then calculated the LPIPS for center regions. The code is as follows: `

import argparse
import os
from util import util
import models.dist_model as dm
import random

parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('--dir0', type=str, default='./imgs/ex_dir0')
parser.add_argument('--dir1', type=str, default='./imgs/ex_dir1')
parser.add_argument('--out', type=str, default='./imgs/example_dists_mask.txt')
parser.add_argument('--use_gpu', action='store_true', help='turn on flag to use GPU')
opt = parser.parse_args()

model = dm.DistModel()
model.initialize(model='net-lin',net='alex',use_gpu=opt.use_gpu)

f = open(opt.out,'w')
files = sorted(os.listdir(opt.dir0))
dist_sum = 0
i = 0
size = len(files)

for i in range(50000):
	if(os.path.exists(os.path.join(opt.dir1,files[i]))):
		img0 = util.im2tensor(util.load_image(os.path.join(opt.dir0, files[i]))) # RGB image from [-1,1]
		img1 = util.im2tensor(util.load_image(os.path.join(opt.dir1, files[i])))

		center_img0 = img0[:, :, 64:192, 64:192]
		center_img1 = img1[:, :, 64:192, 64:192]
		dist01 = model.forward(center_img0, center_img1)
		dist_sum += dist01
		if i % 1000 ==0:
			print('%d, %.6f' % (i, dist_sum / i))
			f.writelines('%s: %.6f\n' % (files[i], dist_sum / i))
		print('%s: %.3f'%(files[i], dist01))
		f.writelines('%s: %.6f\n'%(files[i], dist01))
		i += 1

print('%d, %.6f' % (i, dist_sum / i))

f.close()`

**Comment by laolongboy** [comment]
> Hi @laolongboy, for the diversity score, we only calculate the LPIPS for the center regions. Besides, we sampled 50K pairs in two files and then calculated the LPIPS for center regions. The code is as follows: `
> 
> import argparse
> import os
> from util import util
> import models.dist_model as dm
> import random
> 
> parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
> parser.add_argument('--dir0', type=str, default='./imgs/ex_dir0')
> parser.add_argument('--dir1', type=str, default='./imgs/ex_dir1')
> parser.add_argument('--out', type=str, default='./imgs/example_dists_mask.txt')
> parser.add_argument('--use_gpu', action='store_true', help='turn on flag to use GPU')
> opt = parser.parse_args()
> 
> model = dm.DistModel()
> model.initialize(model='net-lin',net='alex',use_gpu=opt.use_gpu)
> 
> f = open(opt.out,'w')
> files = sorted(os.listdir(opt.dir0))
> dist_sum = 0
> i = 0
> size = len(files)
> 
> for i in range(50000):
> if(os.path.exists(os.path.join(opt.dir1,files[i]))):
> img0 = util.im2tensor(util.load_image(os.path.join(opt.dir0, files[i]))) # RGB image from [-1,1]
> img1 = util.im2tensor(util.load_image(os.path.join(opt.dir1, files[i])))
> 
> ```
> 	center_img0 = img0[:, :, 64:192, 64:192]
> 	center_img1 = img1[:, :, 64:192, 64:192]
> 	dist01 = model.forward(center_img0, center_img1)
> 	dist_sum += dist01
> 	if i % 1000 ==0:
> 		print('%d, %.6f' % (i, dist_sum / i))
> 		f.writelines('%s: %.6f\n' % (files[i], dist_sum / i))
> 	print('%s: %.3f'%(files[i], dist01))
> 	f.writelines('%s: %.6f\n'%(files[i], dist01))
> 	i += 1
> ```
> 
> print('%d, %.6f' % (i, dist_sum / i))
> 
> f.close()`

Thanks! Can you correct the format?

**Comment by pangPhD** [comment]
How do you achieve a variety of complete images? Why is my completed picture very simple
