### ISSUE TITLE
About pre-trained model

### ISSUE THREAD

**Issue by huytran19** [lyndonzheng/Pluralistic-Inpainting#60]
I want to test your project so I downloaded your pre-trained model, but result image is different, it is just define the mask that I drew, please explain for me, please.

**Comment by lyndonzheng** [comment]
Hi @huytran19, This is a duplicate of https://github.com/lyndonzheng/Pluralistic-Inpainting/issues/9 and https://github.com/lyndonzheng/Pluralistic-Inpainting/issues/40
