### ISSUE TITLE
How can we get the loss plot of testing and training

### ISSUE THREAD

**Issue by twyunting** [lyndonzheng/Pluralistic-Inpainting#62]
Hello, @lyndonzheng! Thank you for your fantastic code. In my computer vision class, I will present your paper as part of my final project.

When I ran the code on Colab, I only can see the `loss_log.txt` in the `checkpoints` local folder. How can we get the loss plot? thanks

**Comment by lyndonzheng** [comment]
Hi @twyunting, during the training, we use the [visdom](https://github.com/fossasia/visdom) and [dominate](https://github.com/Knio/dominate) to visualize the image and loss plot. But I am not sure whether they are available on Colab.

**Comment by twyunting** [comment]
Hi @lyndonzheng. Thanks so much for answering. I will try it.

**Comment by nisailgunn** [comment]
Hello, can you share the google colab link with me?
