### ISSUE TITLE
about kl_rec

### ISSUE THREAD

**Issue by liuliuliu11** [lyndonzheng/Pluralistic-Inpainting#63]
Thanks for your work. i want to ask for help about kl_rec.
https://github.com/lyndonzheng/Pluralistic-Inpainting/blob/1ca1855615fed8b686ca218c6494f455860f9996/model/pluralistic_model.py#L99
1. kl_rec regularizes the learned importance sampling function qψ (·|I c ) to a fixed latent prior p(z c ).Shouldn't `kl_rec += torch.distributions.kl_divergence(m_distribution, p_distribution)` is kl_rec += torch.distributions.kl_divergence(p_distribution, m_distribution)?
2. what is the role of https://github.com/lyndonzheng/Pluralistic-Inpainting/blob/1ca1855615fed8b686ca218c6494f455860f9996/model/pluralistic_model.py#L102 and https://github.com/lyndonzheng/Pluralistic-Inpainting/blob/1ca1855615fed8b686ca218c6494f455860f9996/model/pluralistic_model.py#L103?
3. in my work, without using VAE or CVAE, how to calculate the distribution feature map from a similar encoder model and the Parameters of the distribution？

**Comment by ddlee-cn** [comment]
I can help with the second question. It's designed for encouraging more variance for larger holes(more valid pixels, less sigma), as explained in the paragraph below the Fig. 3 in the paper.

**Comment by liuliuliu11** [comment]
> 
> 
> I can help with the second question. It's designed for encouraging more variance for larger holes(more valid pixels, less sigma), as explained in the paragraph below the Fig. 3 in the paper.

thanks~
