### ISSUE TITLE
color discrepancy

### ISSUE THREAD

**Issue by 1900zyh** [lyndonzheng/Pluralistic-Inpainting#7]
I have tried your model. It's really amazing. 
Thank you for your code, demo and paper, thank you for your work!

However, I found that the model usually suffers from color discrepancy (especially in Places2/ImageNet) even in simple cases.

Do you have any idea why such problems happened?
And how can we solve or improve it?

Thanks!

**Comment by lyndonzheng** [comment]
@1900zyh Could you provide some examples for your problem? For the free form mask in Place2/ImageNet, the plausible and diverse results are not so impressive. That's what we try to improve in current work.

**Comment by sporterman** [comment]
@lyndonzheng while using free-form place2 model to fill pictures, the results were as below:
![image](https://user-images.githubusercontent.com/13059352/56857762-f1461b00-69a3-11e9-95fe-0d0a589a82ac.png)
![image](https://user-images.githubusercontent.com/13059352/56857776-18045180-69a4-11e9-8f36-b019cb4c74d9.png)

 at edge of mask area, it always appear dotted line, what's wrong?

**Comment by lyndonzheng** [comment]
@1900zyh You can search the RGB-A output for image decomposition. I guess this problem comes from that the boundary is unclear for the mask regions. You can try to add the mask region a little larger than the object. Besides, what's the input size for your testing?
