### ISSUE TITLE
how can i generate different image?

### ISSUE THREAD

**Issue by 2018hello** [lyndonzheng/Pluralistic-Inpainting#8]
hi 
I see in the paper, in figure 1, there are a lot of images which generated from the same image and the same mask.
How can I achieve these results? Should I change any  input in test?

Thanks!

**Comment by lyndonzheng** [comment]
@2018hello If you directly use the test.py, we provides 50 outputs, which can be set in the test_options.py file. If you use the GUI tool from ui_main.py, you can click the 'fill' button many times to get different outputs.
